FROM maven:3.5.4-jdk-8-alpine as maven

COPY src /home/seleniumTestFramework/src

COPY pom.xml /home/seleniumTestFramework

COPY TestNG.xml /home/seleniumTestFramework

RUN  mvn -f /home/seleniumTestFramework/pom.xml clean test -DskipTests=true